"""empty message

Revision ID: 150cd1032920
Revises: b32fe3ffea2f
Create Date: 2025-04-12 00:47:17.662853

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '150cd1032920'
down_revision = 'b32fe3ffea2f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('usuario')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('usuario',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('email', sa.VARCHAR(length=120), autoincrement=False, nullable=False),
    sa.Column('password', sa.VARCHAR(length=120), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='usuario_pkey'),
    sa.UniqueConstraint('email', name='usuario_email_key')
    )
    # ### end Alembic commands ###
